### ISSUE TITLE
使用自己数据集时遇到的问题

### ISSUE THREAD

**Issue by w199809** [CompliceU/Bytetrack_yolov7#3]
你好，我自己在yolov7上训练了数据集，我更换了模型和视频后，报这个错

Fusing layers... 
D:\Can\anac_install\envs\torch_can\lib\site-packages\torch\functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
D:\Can\anac_install\envs\torch_can\lib\site-packages\torch\_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:482.)
  return self._grad
0.5 30 0.8 False 25
Traceback (most recent call last):
  File "D:/wbw/Bytetrack_yolov7-master/track_demo.py", line 88, in <module>
    track_demo()
  File "D:/wbw/Bytetrack_yolov7-master/track_demo.py", line 58, in track_demo
    online_targets = tracker.update(np.array(dets), [height, width], (height, width))
  File "D:\wbw\Bytetrack_yolov7-master\tracker\byte_tracker.py", line 169, in update
    if output_results.shape[1] == 5:
IndexError: tuple index out of range

Process finished with exit code 1
请问你知道这是怎么回事吗  谢谢

**Comment by w199809** [comment]
我没有改inference.py文件中的类别  改成我自己的类别就好了

**Comment by CompliceU** [comment]
好的






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CompliceU/Bytetrack_yolov7"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月3日(星期二) 下午4:09
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [CompliceU/Bytetrack_yolov7] 使用自己数据集时遇到的问题 (Issue #3)





 
我没有改inference.py文件中的类别  改成我自己的类别就好了
